19-10-2020 10:32:47 C:\Users\User\Desktop\sensors_bridge\data\15_10_2020_dissolvedoxygen.txt removed
19-10-2020 10:32:47 C:\Users\User\Desktop\sensors_bridge\data\15_10_2020_meteorology.txt removed
19-10-2020 10:32:47 C:\Users\User\Desktop\sensors_bridge\data\16_10_2020_dissolvedoxygen.txt removed
19-10-2020 10:32:47 C:\Users\User\Desktop\sensors_bridge\data\log_15_10_2020.txt removed
19-10-2020 10:32:47 C:\Users\User\Desktop\sensors_bridge\data\log_16_10_2020.txt removed
19-10-2020 10:32:47 Sensors Bridge connected to port 50000
19-10-2020 10:32:47 Sensors Bridge connected to co2procv (COM3)
19-10-2020 10:32:49 Sensors Bridge connected to ecotriplet1 (COM4)
19-10-2020 10:32:51 Sensors Bridge connected to ecotriplet2 (COM5)
19-10-2020 10:32:54 Sensors Bridge connected to ecotriplet3 (COM6)
19-10-2020 10:32:55 Sensors Bridge connected to dissolvedoxygen (COM7)
19-10-2020 10:37:16 Sensors Bridge connected to port 50000
19-10-2020 10:37:16 Sensors Bridge connected to co2procv (COM3)
19-10-2020 10:37:18 Sensors Bridge connected to ecotriplet1 (COM4)
19-10-2020 10:37:20 Sensors Bridge connected to ecotriplet2 (COM5)
19-10-2020 10:37:21 Sensors Bridge connected to ecotriplet3 (COM6)
19-10-2020 10:37:23 Sensors Bridge connected to dissolvedoxygen (COM7)
19-10-2020 10:39:53 Sensors Bridge connected to port 50000
19-10-2020 10:39:53 Sensors Bridge connected to co2procv (COM3)
19-10-2020 10:39:55 Sensors Bridge connected to ecotriplet1 (COM4)
19-10-2020 10:39:57 Sensors Bridge connected to ecotriplet2 (COM5)
19-10-2020 10:39:59 Sensors Bridge connected to ecotriplet3 (COM6)
19-10-2020 10:40:02 Sensors Bridge connected to dissolvedoxygen (COM7)
19-10-2020 10:44:29 Sensors Bridge connected to port 50000
19-10-2020 10:44:29 Sensors Bridge connected to co2procv (COM3)
19-10-2020 10:44:31 Sensors Bridge connected to ecotriplet1 (COM4)
19-10-2020 10:44:33 Sensors Bridge connected to ecotriplet2 (COM5)
19-10-2020 10:44:35 Sensors Bridge connected to ecotriplet3 (COM6)
19-10-2020 10:44:37 Sensors Bridge connected to dissolvedoxygen (COM7)
19-10-2020 10:45:56 Error: 500 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 10:46:18 Error: 500 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 10:46:42 Error: 500 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 10:47:02 Error: 500 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 10:47:33 Error: 500 Failed to send wind at port WIMWV. Saving it to local file.
19-10-2020 10:47:46 Error: 500 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 10:48:07 Error: 500 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 10:48:28 Error: 500 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 10:49:21 Error: 500 Failed to send wind at port WIMWV. Saving it to local file.
19-10-2020 10:49:42 Error: 500 Failed to send wind at port WIMWV. Saving it to local file.
19-10-2020 10:50:02 Error: 500 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 10:54:27 Sensors Bridge connected to port 50000
19-10-2020 10:54:27 Sensors Bridge connected to co2procv (COM3)
19-10-2020 10:54:28 Sensors Bridge connected to ecotriplet1 (COM4)
19-10-2020 10:54:28 Sensors Bridge connected to ecotriplet2 (COM5)
19-10-2020 10:54:29 Sensors Bridge connected to ecotriplet3 (COM6)
19-10-2020 10:54:29 Sensors Bridge connected to dissolvedoxygen (COM7)
19-10-2020 10:54:33 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 10:54:33 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 10:54:33 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 10:54:33 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 10:54:33 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 10:54:33 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 10:54:34 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 10:54:34 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 10:56:08 Sensors Bridge connected to port 50000
19-10-2020 10:56:08 Sensors Bridge connected to co2procv (COM3)
19-10-2020 10:56:09 Sensors Bridge connected to ecotriplet1 (COM4)
19-10-2020 10:56:10 Sensors Bridge connected to ecotriplet2 (COM5)
19-10-2020 10:56:11 Sensors Bridge connected to ecotriplet3 (COM6)
19-10-2020 10:56:12 Sensors Bridge connected to dissolvedoxygen (COM7)
19-10-2020 10:56:16 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 10:56:16 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 10:56:16 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 10:56:17 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 10:56:17 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 10:56:17 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 10:56:17 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 10:56:17 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 10:58:03 Error: 500 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 10:59:37 Error: 500 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 10:59:58 Error: 500 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 11:00:19 Error: 500 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 11:01:32 Error: 500 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 11:01:53 Error: 500 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 11:02:14 Error: 500 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 11:02:35 Error: 500 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 11:03:23 Sensors Bridge connected to port 50000
19-10-2020 11:03:23 Sensors Bridge connected to co2procv (COM3)
19-10-2020 11:03:24 Sensors Bridge connected to ecotriplet1 (COM4)
19-10-2020 11:03:25 Sensors Bridge connected to ecotriplet2 (COM5)
19-10-2020 11:03:25 Sensors Bridge connected to ecotriplet3 (COM6)
19-10-2020 11:03:26 Sensors Bridge connected to dissolvedoxygen (COM7)
19-10-2020 11:03:29 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 11:03:30 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 11:03:30 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 11:03:30 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 11:03:30 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 11:03:30 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 11:03:33 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 11:03:33 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 11:03:48 Error: 500 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 11:04:09 Error: 500 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 11:04:30 Error: 500 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 11:05:30 Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Python38\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\Python38\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Python38\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "C:\Python38\lib\site-packages\urllib3\util\retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Python38\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Python38\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\Python38\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Python38\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 298, in read_com
    manage_data(data, com, show_no_internet_error)
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 319, in manage_data
    send_temp_files_by_com(port_name)
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 144, in send_temp_files_by_com
    result = send_to_server(com, data)
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 103, in send_to_server
    response = SESSION.post(url, data=data)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python38\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

19-10-2020 11:05:30 Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Python38\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\Python38\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Python38\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "C:\Python38\lib\site-packages\urllib3\util\retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Python38\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Python38\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\Python38\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Python38\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 298, in read_com
    manage_data(data, com, show_no_internet_error)
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 319, in manage_data
    send_temp_files_by_com(port_name)
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 144, in send_temp_files_by_com
    result = send_to_server(com, data)
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 103, in send_to_server
    response = SESSION.post(url, data=data)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python38\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

19-10-2020 11:05:43 Error: 500 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 11:06:04 Error: 500 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 11:06:25 Error: 500 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 11:06:46 Error: 500 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 11:07:38 Error: 500 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 11:07:59 Error: 500 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 11:08:20 Error: 500 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 11:08:41 Error: 500 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 11:09:34 Error: 500 Failed to send wind at port WIMWV. Saving it to local file.
19-10-2020 11:09:54 Error: 500 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 11:10:15 Error: 500 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 11:10:36 Error: 500 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 11:18:06 Sensors Bridge connected to port 50000
19-10-2020 11:18:06 Sensors Bridge connected to co2procv (COM3)
19-10-2020 11:18:06 Sensors Bridge connected to ecotriplet1 (COM4)
19-10-2020 11:18:07 Sensors Bridge connected to ecotriplet2 (COM5)
19-10-2020 11:18:08 Sensors Bridge connected to ecotriplet3 (COM6)
19-10-2020 11:18:08 Sensors Bridge connected to dissolvedoxygen (COM7)
19-10-2020 11:18:12 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 11:18:12 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 11:18:12 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 11:18:13 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 11:18:13 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
n.txt
19-10-2020 11:18:13 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 11:18:13 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 11:20:11 Error: 500 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 11:20:13 Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Python38\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\Python38\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Python38\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "C:\Python38\lib\site-packages\urllib3\util\retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Python38\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Python38\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\Python38\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Python38\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 298, in read_com
    manage_data(data, com, show_no_internet_error)
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 319, in manage_data
    send_temp_files_by_com(port_name)
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 144, in send_temp_files_by_com
    result = send_to_server(com, data)
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 103, in send_to_server
    response = SESSION.post(url, data=data)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python38\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

19-10-2020 11:20:13 Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Python38\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\Python38\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Python38\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "C:\Python38\lib\site-packages\urllib3\util\retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Python38\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Python38\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\Python38\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Python38\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 298, in read_com
    manage_data(data, com, show_no_internet_error)
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 319, in manage_data
    send_temp_files_by_com(port_name)
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 144, in send_temp_files_by_com
    result = send_to_server(com, data)
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 103, in send_to_server
    response = SESSION.post(url, data=data)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python38\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

19-10-2020 11:21:45 Error: 500 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 11:22:06 Error: 500 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 11:22:27 Error: 500 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 11:22:56 Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Python38\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\Python38\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Python38\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "C:\Python38\lib\site-packages\urllib3\util\retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Python38\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Python38\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\Python38\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Python38\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 298, in read_com
    manage_data(data, com, show_no_internet_error)
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 310, in manage_data
    send_to_server(port_name, data)
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 103, in send_to_server
    response = SESSION.post(url, data=data)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python38\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

19-10-2020 11:23:05 Error: 503 Failed to send wind at port WIMWV. Saving it to local file.
19-10-2020 11:23:05 Error: 503 Failed to send ecotriplet1 at port COM4. Saving it to local file.
19-10-2020 11:23:05 Error: 503 Failed to send ecotriplet2 at port COM5. Saving it to local file.
19-10-2020 11:23:40 Error: 500 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 11:24:02 Error: 500 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 11:24:22 Error: 500 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 11:25:36 Error: 500 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 11:25:57 Error: 500 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 11:26:18 Error: 500 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 11:30:55 Sensors Bridge connected to port 50000
19-10-2020 11:30:55 Sensors Bridge connected to co2procv (COM3)
19-10-2020 11:30:56 Sensors Bridge connected to ecotriplet1 (COM4)
19-10-2020 11:30:56 Sensors Bridge connected to ecotriplet2 (COM5)
19-10-2020 11:30:57 Sensors Bridge connected to ecotriplet3 (COM6)
19-10-2020 11:30:58 Sensors Bridge connected to dissolvedoxygen (COM7)
19-10-2020 11:31:01 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 11:31:01 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 11:31:02 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 11:31:02 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 11:31:02 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 11:31:02 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 11:31:02 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 11:31:02 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 11:32:03 Error: 500 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 11:32:23 Error: 500 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 11:32:44 Error: 500 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 11:33:02 Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Python38\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\Python38\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Python38\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "C:\Python38\lib\site-packages\urllib3\util\retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Python38\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Python38\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\Python38\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Python38\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 298, in read_com
    manage_data(data, com, show_no_internet_error)
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 319, in manage_data
    send_temp_files_by_com(port_name)
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 144, in send_temp_files_by_com
    result = send_to_server(com, data)
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 103, in send_to_server
    response = SESSION.post(url, data=data)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python38\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

19-10-2020 11:33:02 Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Python38\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\Python38\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Python38\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "C:\Python38\lib\site-packages\urllib3\util\retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Python38\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Python38\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\Python38\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Python38\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 298, in read_com
    manage_data(data, com, show_no_internet_error)
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 319, in manage_data
    send_temp_files_by_com(port_name)
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 144, in send_temp_files_by_com
    result = send_to_server(com, data)
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 103, in send_to_server
    response = SESSION.post(url, data=data)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python38\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

19-10-2020 11:33:37 Error: 500 Failed to send wind at port WIMWV. Saving it to local file.
19-10-2020 11:33:57 Error: 500 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 11:34:19 Error: 500 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 11:35:11 Error: 500 Failed to send wind at port WIMWV. Saving it to local file.
19-10-2020 11:35:32 Error: 500 Failed to send wind at port WIMWV. Saving it to local file.
19-10-2020 11:36:14 Error: 500 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 11:37:06 Error: 500 Failed to send wind at port WIMWV. Saving it to local file.
19-10-2020 11:38:38 Sensors Bridge connected to port 50000
19-10-2020 11:38:38 Sensors Bridge connected to co2procv (COM3)
19-10-2020 11:38:39 Sensors Bridge connected to ecotriplet1 (COM4)
19-10-2020 11:38:40 Sensors Bridge connected to ecotriplet2 (COM5)
19-10-2020 11:38:40 Sensors Bridge connected to ecotriplet3 (COM6)
19-10-2020 11:38:41 Sensors Bridge connected to dissolvedoxygen (COM7)
19-10-2020 11:38:44 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 11:38:45 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 11:38:45 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 11:38:45 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 11:38:45 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 11:38:45 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 11:38:45 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 11:38:45 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 11:38:45 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 11:38:46 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 11:38:51 Error: 500 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 11:39:11 Error: 500 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 11:39:33 Error: 500 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 11:40:25 Error: 500 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 11:40:46 Error: 500 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 11:41:07 Error: 500 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 11:41:27 Error: 500 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 11:42:39 Sensors Bridge connected to port 50000
19-10-2020 11:42:39 Sensors Bridge connected to co2procv (COM3)
19-10-2020 11:42:40 Sensors Bridge connected to ecotriplet1 (COM4)
19-10-2020 11:42:41 Sensors Bridge connected to ecotriplet2 (COM5)
19-10-2020 11:42:41 Sensors Bridge connected to ecotriplet3 (COM6)
19-10-2020 11:42:42 Sensors Bridge connected to dissolvedoxygen (COM7)
19-10-2020 11:42:46 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 11:42:46 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 11:42:46 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 11:42:46 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 11:42:46 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 11:42:46 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 11:42:46 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 11:42:46 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 11:42:46 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 11:42:47 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 11:43:02 Error: 500 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 11:43:54 Error: 500 Failed to send wind at port WIMWV. Saving it to local file.
19-10-2020 11:44:15 Error: 500 Failed to send wind at port WIMWV. Saving it to local file.
19-10-2020 11:44:37 Sensors Bridge connected to port 50000
19-10-2020 11:44:37 Sensors Bridge connected to co2procv (COM3)
19-10-2020 11:44:38 Sensors Bridge connected to ecotriplet1 (COM4)
19-10-2020 11:44:39 Sensors Bridge connected to ecotriplet2 (COM5)
19-10-2020 11:44:40 Sensors Bridge connected to ecotriplet3 (COM6)
19-10-2020 11:44:40 Sensors Bridge connected to dissolvedoxygen (COM7)
19-10-2020 11:44:44 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 11:44:45 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 11:44:45 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 11:44:45 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 11:44:45 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 11:44:45 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 11:44:45 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 11:44:45 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 11:44:45 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 11:44:45 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 11:44:56 Error: 500 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 11:45:20 Error: 503 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 11:45:21 Error: 503 Failed to send wind at port WIMWV. Saving it to local file.
19-10-2020 11:45:29 Error: 503 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 11:45:30 Error: 503 Failed to send wind at port WIMWV. Saving it to local file.
19-10-2020 11:45:31 Error: 503 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 11:45:32 Error: 503 Failed to send wind at port WIMWV. Saving it to local file.
19-10-2020 11:45:32 Error: 503 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 11:45:33 Error: 503 Failed to send wind at port WIMWV. Saving it to local file.
19-10-2020 11:45:33 Error: 503 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 11:45:34 Error: 503 Failed to send wind at port WIMWV. Saving it to local file.
19-10-2020 11:45:34 Error: 503 Failed to send meteorology at port WIMDA. Saving it to local file.
19-10-2020 11:45:35 Error: 503 Failed to send wind at port WIMWV. Saving it to local file.
19-10-2020 11:45:49 Sensors Bridge connected to port 50000
19-10-2020 11:45:49 Sensors Bridge connected to co2procv (COM3)
19-10-2020 11:45:50 Sensors Bridge connected to ecotriplet1 (COM4)
19-10-2020 11:45:50 Sensors Bridge connected to ecotriplet2 (COM5)
19-10-2020 11:45:51 Sensors Bridge connected to ecotriplet3 (COM6)
19-10-2020 11:45:52 Sensors Bridge connected to dissolvedoxygen (COM7)
19-10-2020 11:45:55 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 11:45:55 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 11:45:55 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 11:45:56 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 11:45:56 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 11:45:56 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 11:45:56 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 11:45:56 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 11:45:56 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 11:45:56 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 11:46:10 Error: 500 Failed to send wind at port WIMWV. Saving it to local file.
19-10-2020 11:46:31 Error: 500 Failed to send wind at port WIMWV. Saving it to local file.
19-10-2020 11:47:23 Error: 500 Failed to send wind at port WIMWV. Saving it to local file.
19-10-2020 11:47:44 Error: 500 Failed to send wind at port WIMWV. Saving it to local file.
19-10-2020 11:48:05 Error: 500 Failed to send wind at port WIMWV. Saving it to local file.
19-10-2020 11:49:39 Error: 500 Failed to send wind at port WIMWV. Saving it to local file.
19-10-2020 11:50:18 Error: 503 Failed to send wind at port WIMWV. Saving it to local file.
19-10-2020 11:50:38 Sensors Bridge connected to port 50000
19-10-2020 11:50:38 Sensors Bridge connected to co2procv (COM3)
19-10-2020 11:50:39 Sensors Bridge connected to ecotriplet1 (COM4)
19-10-2020 11:50:39 Sensors Bridge connected to ecotriplet2 (COM5)
19-10-2020 11:50:40 Sensors Bridge connected to ecotriplet3 (COM6)
19-10-2020 11:50:41 Sensors Bridge connected to dissolvedoxygen (COM7)
19-10-2020 11:50:44 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 11:50:44 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 11:50:45 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 11:50:45 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 11:50:45 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 11:50:45 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 11:50:45 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 11:50:45 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 11:50:45 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 11:50:45 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 11:57:06 Sensors Bridge connected to port 50000
19-10-2020 11:57:06 Sensors Bridge connected to co2procv (COM3)
19-10-2020 11:57:07 Sensors Bridge connected to ecotriplet1 (COM4)
19-10-2020 11:57:07 Sensors Bridge connected to ecotriplet2 (COM5)
19-10-2020 11:57:08 Sensors Bridge connected to ecotriplet3 (COM6)
19-10-2020 11:57:09 Sensors Bridge connected to dissolvedoxygen (COM7)
19-10-2020 11:57:12 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 11:57:13 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 11:57:13 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 11:57:13 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 11:57:13 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 11:57:13 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 11:57:13 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 11:57:13 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 11:57:13 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 11:57:13 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 11:59:35 Sensors Bridge connected to port 50000
19-10-2020 11:59:35 Sensors Bridge connected to co2procv (COM3)
19-10-2020 11:59:36 Sensors Bridge connected to ecotriplet1 (COM4)
19-10-2020 11:59:37 Sensors Bridge connected to ecotriplet2 (COM5)
19-10-2020 11:59:37 Sensors Bridge connected to ecotriplet3 (COM6)
19-10-2020 11:59:38 Sensors Bridge connected to dissolvedoxygen (COM7)
19-10-2020 11:59:42 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 11:59:42 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 11:59:42 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 11:59:42 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 11:59:42 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 11:59:42 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 11:59:42 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 11:59:42 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 11:59:42 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 11:59:43 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 12:01:30 Sensors Bridge connected to port 50000
19-10-2020 12:01:30 Sensors Bridge connected to co2procv (COM3)
19-10-2020 12:01:31 Sensors Bridge connected to ecotriplet1 (COM4)
19-10-2020 12:01:32 Sensors Bridge connected to ecotriplet2 (COM5)
19-10-2020 12:01:33 Sensors Bridge connected to ecotriplet3 (COM6)
19-10-2020 12:01:33 Sensors Bridge connected to dissolvedoxygen (COM7)
19-10-2020 12:01:37 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 12:01:37 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 12:01:37 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 12:01:38 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 12:01:38 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 12:01:38 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 12:01:38 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 12:01:38 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 12:01:38 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 12:01:38 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 12:02:11 Sensors Bridge connected to port 50000
19-10-2020 12:02:11 Sensors Bridge connected to co2procv (COM3)
19-10-2020 12:02:12 Sensors Bridge connected to ecotriplet1 (COM4)
19-10-2020 12:02:12 Sensors Bridge connected to ecotriplet2 (COM5)
19-10-2020 12:02:13 Sensors Bridge connected to ecotriplet3 (COM6)
19-10-2020 12:02:14 Sensors Bridge connected to dissolvedoxygen (COM7)
19-10-2020 12:04:09 Sensors Bridge connected to co2procv (COM3)
19-10-2020 12:04:10 Sensors Bridge connected to ecotriplet1 (COM4)
19-10-2020 12:04:10 Sensors Bridge connected to ecotriplet2 (COM5)
19-10-2020 12:04:11 Sensors Bridge connected to ecotriplet3 (COM6)
19-10-2020 12:04:12 Sensors Bridge connected to dissolvedoxygen (COM7)
19-10-2020 12:04:15 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 12:04:16 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 12:04:16 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 12:04:16 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 12:04:16 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 12:04:16 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 12:04:16 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 12:04:16 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 12:04:16 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 12:04:16 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 12:06:01 Sensors Bridge connected to co2procv (COM3)
19-10-2020 12:06:02 Sensors Bridge connected to ecotriplet1 (COM4)
19-10-2020 12:06:02 Sensors Bridge connected to ecotriplet2 (COM5)
19-10-2020 12:06:03 Sensors Bridge connected to ecotriplet3 (COM6)
19-10-2020 12:06:04 Sensors Bridge connected to dissolvedoxygen (COM7)
19-10-2020 12:06:08 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 12:06:08 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 12:06:08 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 12:06:08 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 12:06:08 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 12:06:08 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 12:06:08 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 12:06:08 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 12:06:09 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 12:06:09 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 12:06:57 Sensors Bridge connected to co2procv (COM3)
19-10-2020 12:06:57 Sensors Bridge connected to ecotriplet1 (COM4)
19-10-2020 12:06:58 Sensors Bridge connected to ecotriplet2 (COM5)
19-10-2020 12:06:59 Sensors Bridge connected to ecotriplet3 (COM6)
19-10-2020 12:06:59 Sensors Bridge connected to dissolvedoxygen (COM7)
19-10-2020 12:07:03 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 12:07:03 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 12:07:03 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 12:07:03 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 12:07:03 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 12:07:04 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 12:07:04 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 12:07:04 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 12:07:04 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 12:07:04 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 12:08:34 Sensors Bridge connected to co2procv (COM3)
19-10-2020 12:08:34 Sensors Bridge connected to ecotriplet1 (COM4)
19-10-2020 12:08:35 Sensors Bridge connected to ecotriplet2 (COM5)
19-10-2020 12:08:36 Sensors Bridge connected to ecotriplet3 (COM6)
19-10-2020 12:08:37 Sensors Bridge connected to dissolvedoxygen (COM7)
19-10-2020 12:09:36 Sensors Bridge connected to co2procv (COM3)
19-10-2020 12:09:36 Sensors Bridge connected to ecotriplet1 (COM4)
19-10-2020 12:09:37 Sensors Bridge connected to ecotriplet2 (COM5)
19-10-2020 12:09:38 Sensors Bridge connected to ecotriplet3 (COM6)
19-10-2020 12:09:39 Sensors Bridge connected to dissolvedoxygen (COM7)
19-10-2020 12:09:42 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 12:09:42 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 12:09:42 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 12:09:43 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 12:09:43 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 12:09:43 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 12:09:43 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 12:09:43 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 12:09:43 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 12:09:43 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 12:10:53 Sensors Bridge connected to co2procv (COM3)
19-10-2020 12:10:54 Sensors Bridge connected to ecotriplet1 (COM4)
19-10-2020 12:10:54 Sensors Bridge connected to ecotriplet2 (COM5)
19-10-2020 12:10:55 Sensors Bridge connected to ecotriplet3 (COM6)
19-10-2020 12:10:56 Sensors Bridge connected to dissolvedoxygen (COM7)
19-10-2020 12:11:00 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 12:11:00 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 12:11:00 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 12:11:00 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 12:11:00 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 12:11:00 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 12:11:00 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 12:11:01 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 12:11:01 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 12:11:01 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 12:16:08 C:\Users\User\Desktop\sensors_bridge\data\16_10_2020_gpsposition.txt removed
19-10-2020 12:16:08 Sensors Bridge connected to co2procv (COM3)
19-10-2020 12:16:09 Sensors Bridge connected to ecotriplet1 (COM4)
19-10-2020 12:16:10 Sensors Bridge connected to ecotriplet2 (COM5)
19-10-2020 12:16:10 Sensors Bridge connected to ecotriplet3 (COM6)
19-10-2020 12:16:11 Sensors Bridge connected to dissolvedoxygen (COM7)
19-10-2020 12:16:15 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 12:16:15 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 12:16:15 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 12:16:15 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 12:16:15 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 12:16:15 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 12:16:16 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 12:16:16 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 12:16:16 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 12:16:16 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 12:17:28 Sensors Bridge connected to co2procv (COM3)
19-10-2020 12:17:29 Sensors Bridge connected to ecotriplet1 (COM4)
19-10-2020 12:17:30 Sensors Bridge connected to ecotriplet2 (COM5)
19-10-2020 12:17:30 Sensors Bridge connected to ecotriplet3 (COM6)
19-10-2020 12:17:31 Sensors Bridge connected to dissolvedoxygen (COM7)
19-10-2020 12:17:35 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 12:17:35 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 12:17:36 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 12:17:36 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 12:17:36 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 12:17:36 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 12:17:36 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 12:17:36 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 12:17:37 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 12:17:37 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 12:19:19 Sensors Bridge connected to co2procv (COM3)
19-10-2020 12:19:20 Sensors Bridge connected to ecotriplet1 (COM4)
19-10-2020 12:19:20 Sensors Bridge connected to ecotriplet2 (COM5)
19-10-2020 12:19:21 Sensors Bridge connected to ecotriplet3 (COM6)
19-10-2020 12:19:22 Sensors Bridge connected to dissolvedoxygen (COM7)
19-10-2020 12:19:25 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 12:19:26 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 12:19:26 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 12:19:26 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 12:19:26 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 12:19:26 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 12:19:26 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 12:19:26 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 12:19:27 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 12:19:27 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 12:27:27 Sensors Bridge connected to co2procv (COM3)
19-10-2020 12:27:28 Sensors Bridge connected to ecotriplet1 (COM4)
19-10-2020 12:27:29 Sensors Bridge connected to ecotriplet2 (COM5)
19-10-2020 12:27:30 Sensors Bridge connected to ecotriplet3 (COM6)
19-10-2020 12:27:31 Sensors Bridge connected to dissolvedoxygen (COM7)
19-10-2020 12:27:34 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 12:27:34 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 12:27:34 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 12:27:35 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 12:27:35 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 12:27:35 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 12:27:35 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 12:27:35 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 12:27:35 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 12:27:35 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 12:33:39 Sensors Bridge connected to co2procv (COM3)
19-10-2020 12:33:40 Sensors Bridge connected to ecotriplet1 (COM4)
19-10-2020 12:33:41 Sensors Bridge connected to ecotriplet2 (COM5)
19-10-2020 12:33:42 Sensors Bridge connected to ecotriplet3 (COM6)
19-10-2020 12:33:42 Sensors Bridge connected to dissolvedoxygen (COM7)
19-10-2020 12:33:46 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 12:33:46 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 12:33:46 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 12:33:46 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 12:33:47 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 12:33:47 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 12:33:47 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 12:33:47 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 12:33:47 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 12:33:48 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 12:35:58 Sensors Bridge connected to co2procv (COM3)
19-10-2020 12:35:59 Sensors Bridge connected to ecotriplet1 (COM4)
19-10-2020 12:36:00 Sensors Bridge connected to ecotriplet2 (COM5)
19-10-2020 12:36:01 Sensors Bridge connected to ecotriplet3 (COM6)
19-10-2020 12:36:02 Sensors Bridge connected to dissolvedoxygen (COM7)
19-10-2020 12:36:06 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 12:36:06 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 12:36:06 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 12:36:06 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 12:36:06 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 12:36:06 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 12:36:06 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 12:36:06 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 12:36:06 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 12:36:07 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 12:38:16 Sensors Bridge connected to co2procv (COM3)
19-10-2020 12:38:16 Sensors Bridge connected to ecotriplet1 (COM4)
19-10-2020 12:38:17 Sensors Bridge connected to ecotriplet2 (COM5)
19-10-2020 12:38:18 Sensors Bridge connected to ecotriplet3 (COM6)
19-10-2020 12:38:19 Sensors Bridge connected to dissolvedoxygen (COM7)
19-10-2020 12:38:23 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 12:38:23 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 12:38:23 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 12:38:23 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 12:38:23 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 12:38:23 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 12:38:23 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 12:38:23 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 12:38:24 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 12:38:24 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 12:40:00 Sensors Bridge connected to co2procv (COM3)
19-10-2020 12:40:01 Sensors Bridge connected to ecotriplet1 (COM4)
19-10-2020 12:40:02 Sensors Bridge connected to ecotriplet2 (COM5)
19-10-2020 12:40:02 Sensors Bridge connected to ecotriplet3 (COM6)
19-10-2020 12:40:03 Sensors Bridge connected to dissolvedoxygen (COM7)
19-10-2020 12:40:07 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 12:40:08 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 12:40:08 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 12:40:08 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 12:40:08 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 12:40:08 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 12:40:08 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 12:40:08 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 12:40:08 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 12:40:08 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 12:40:12 Traceback (most recent call last):
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 295, in read_com
    c = a_serial.readline()
  File "C:\Python38\lib\site-packages\serial\serialwin32.py", line 286, in read
    result_ok = win32.GetOverlappedResult(
KeyboardInterrupt

19-10-2020 12:40:13 Traceback (most recent call last):
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 295, in read_com
    c = a_serial.readline()
  File "C:\Python38\lib\site-packages\serial\serialwin32.py", line 286, in read
    result_ok = win32.GetOverlappedResult(
KeyboardInterrupt

19-10-2020 12:40:13 Traceback (most recent call last):
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 295, in read_com
    c = a_serial.readline()
  File "C:\Python38\lib\site-packages\serial\serialwin32.py", line 286, in read
    result_ok = win32.GetOverlappedResult(
KeyboardInterrupt

19-10-2020 12:40:13 Traceback (most recent call last):
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 295, in read_com
    c = a_serial.readline()
  File "C:\Python38\lib\site-packages\serial\serialwin32.py", line 286, in read
    result_ok = win32.GetOverlappedResult(
KeyboardInterrupt

19-10-2020 12:40:13 Traceback (most recent call last):
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 295, in read_com
    c = a_serial.readline()
  File "C:\Python38\lib\site-packages\serial\serialwin32.py", line 286, in read
    result_ok = win32.GetOverlappedResult(
KeyboardInterrupt

19-10-2020 12:42:02 Sensors Bridge connected to co2procv (COM3)
19-10-2020 12:42:03 Sensors Bridge connected to ecotriplet1 (COM4)
19-10-2020 12:42:04 Sensors Bridge connected to ecotriplet2 (COM5)
19-10-2020 12:42:05 Sensors Bridge connected to ecotriplet3 (COM6)
19-10-2020 12:42:05 Sensors Bridge connected to dissolvedoxygen (COM7)
19-10-2020 12:42:09 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 12:42:09 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 12:42:09 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 12:42:09 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 12:42:10 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 12:42:10 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 12:42:10 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 12:42:10 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 12:42:10 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 12:42:10 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 12:42:43 Sensors Bridge connected to co2procv (COM3)
19-10-2020 12:42:44 Sensors Bridge connected to ecotriplet1 (COM4)
19-10-2020 12:42:44 Sensors Bridge connected to ecotriplet2 (COM5)
19-10-2020 12:42:45 Sensors Bridge connected to ecotriplet3 (COM6)
19-10-2020 12:42:46 Sensors Bridge connected to dissolvedoxygen (COM7)
19-10-2020 12:42:50 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 12:42:50 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 12:42:50 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 12:42:50 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 12:42:50 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 12:42:50 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 12:42:50 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 12:42:50 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 12:42:51 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 12:42:51 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 12:45:32 Sensors Bridge connected to co2procv (COM3)
19-10-2020 12:45:33 Sensors Bridge connected to ecotriplet1 (COM4)
19-10-2020 12:45:34 Sensors Bridge connected to ecotriplet2 (COM5)
19-10-2020 12:45:35 Sensors Bridge connected to ecotriplet3 (COM6)
19-10-2020 12:45:35 Sensors Bridge connected to dissolvedoxygen (COM7)
19-10-2020 12:45:39 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 12:45:40 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 12:45:40 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 12:45:40 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 12:45:40 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 12:45:40 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 12:45:40 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 12:45:40 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 12:45:40 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 12:45:48 Traceback (most recent call last):
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 295, in read_com
    c = a_serial.readline()
  File "C:\Python38\lib\site-packages\serial\serialwin32.py", line 286, in read
    result_ok = win32.GetOverlappedResult(
KeyboardInterrupt

19-10-2020 12:45:48 Traceback (most recent call last):
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 295, in read_com
    c = a_serial.readline()
  File "C:\Python38\lib\site-packages\serial\serialwin32.py", line 286, in read
    result_ok = win32.GetOverlappedResult(
KeyboardInterrupt

19-10-2020 12:45:48 Traceback (most recent call last):
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 295, in read_com
    c = a_serial.readline()
  File "C:\Python38\lib\site-packages\serial\serialwin32.py", line 286, in read
    result_ok = win32.GetOverlappedResult(
KeyboardInterrupt

19-10-2020 12:45:48 Traceback (most recent call last):
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 295, in read_com
    c = a_serial.readline()
  File "C:\Python38\lib\site-packages\serial\serialwin32.py", line 286, in read
    result_ok = win32.GetOverlappedResult(
KeyboardInterrupt

19-10-2020 12:47:40 Traceback (most recent call last):
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 306, in read_com
    manage_data(data, com, show_no_internet_error)
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 327, in manage_data
    send_temp_files_by_com(port_name)
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 146, in send_temp_files_by_com
    result = send_to_server(com, data)
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 105, in send_to_server
    response = SESSION.post(url, data=data)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python38\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Python38\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\Python38\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Python38\lib\http\client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Python38\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "C:\Python38\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Python38\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt

19-10-2020 12:48:07 Sensors Bridge connected to co2procv (COM3)
19-10-2020 12:48:08 Sensors Bridge connected to ecotriplet1 (COM4)
19-10-2020 12:48:09 Sensors Bridge connected to ecotriplet2 (COM5)
19-10-2020 12:48:10 Sensors Bridge connected to ecotriplet3 (COM6)
19-10-2020 12:48:11 Sensors Bridge connected to dissolvedoxygen (COM7)
19-10-2020 12:48:14 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 12:48:14 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 12:48:15 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 12:48:15 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 12:48:15 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 12:48:15 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 12:48:15 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 12:48:15 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 12:48:15 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 12:50:19 Sensors Bridge connected to co2procv (COM3)
19-10-2020 12:50:20 Sensors Bridge connected to ecotriplet1 (COM4)
19-10-2020 12:50:21 Sensors Bridge connected to ecotriplet2 (COM5)
19-10-2020 12:50:22 Sensors Bridge connected to ecotriplet3 (COM6)
19-10-2020 12:50:22 Sensors Bridge connected to dissolvedoxygen (COM7)
19-10-2020 12:50:26 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 12:50:26 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 12:50:27 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 12:50:27 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 12:50:27 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 12:50:27 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 12:50:27 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 12:50:27 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 12:50:27 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 12:52:28 Sensors Bridge connected to co2procv (COM3)
19-10-2020 12:52:29 Sensors Bridge connected to ecotriplet1 (COM4)
19-10-2020 12:52:29 Sensors Bridge connected to ecotriplet2 (COM5)
19-10-2020 12:52:30 Sensors Bridge connected to ecotriplet3 (COM6)
19-10-2020 12:52:31 Sensors Bridge connected to dissolvedoxygen (COM7)
19-10-2020 12:52:34 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 12:52:34 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 12:52:35 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 12:52:35 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 12:52:35 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 12:52:35 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 12:52:35 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 12:53:50 Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Python38\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\Python38\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Python38\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "C:\Python38\lib\site-packages\urllib3\util\retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Python38\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Python38\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\Python38\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Python38\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 302, in read_com
    manage_data(data, com, show_no_internet_error)
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 314, in manage_data
    send_to_server(port_name, data)
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 105, in send_to_server
    response = SESSION.post(url, data=data)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python38\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

19-10-2020 12:54:35 Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Python38\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\Python38\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Python38\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "C:\Python38\lib\site-packages\urllib3\util\retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Python38\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Python38\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\Python38\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Python38\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 302, in read_com
    manage_data(data, com, show_no_internet_error)
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 323, in manage_data
    send_temp_files_by_com(port_name)
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 146, in send_temp_files_by_com
    result = send_to_server(com, data)
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 105, in send_to_server
    response = SESSION.post(url, data=data)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python38\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

19-10-2020 12:55:34 Error: 503 Failed to send ecotriplet2 at port COM5. Saving it to local file.
19-10-2020 12:55:34 Error: 503 Failed to send ecotriplet1 at port COM4. Saving it to local file.
19-10-2020 13:00:58 Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Python38\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\Python38\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Python38\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "C:\Python38\lib\site-packages\urllib3\util\retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Python38\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Python38\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\Python38\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Python38\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 302, in read_com
    manage_data(data, com, show_no_internet_error)
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 314, in manage_data
    send_to_server(port_name, data)
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 105, in send_to_server
    response = SESSION.post(url, data=data)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python38\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

19-10-2020 13:03:37 Sensors Bridge connected to co2procv (COM3)
19-10-2020 13:03:38 Sensors Bridge connected to ecotriplet1 (COM4)
19-10-2020 13:03:39 Sensors Bridge connected to ecotriplet2 (COM5)
19-10-2020 13:03:39 Sensors Bridge connected to ecotriplet3 (COM6)
19-10-2020 13:03:40 Sensors Bridge connected to dissolvedoxygen (COM7)
19-10-2020 13:03:44 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 13:03:44 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 13:03:44 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 13:03:44 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 13:03:44 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 13:03:44 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 13:03:45 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 13:03:45 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 13:03:45 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 13:03:45 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 13:05:31 Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Python38\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\Python38\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Python38\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "C:\Python38\lib\site-packages\urllib3\util\retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Python38\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Python38\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\Python38\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Python38\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 302, in read_com
    manage_data(data, com, show_no_internet_error)
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 314, in manage_data
    send_to_server(port_name, data)
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 105, in send_to_server
    response = SESSION.post(url, data=data)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python38\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

19-10-2020 13:08:05 Sensors Bridge connected to co2procv (COM3)
19-10-2020 13:08:06 Sensors Bridge connected to ecotriplet1 (COM4)
19-10-2020 13:08:07 Sensors Bridge connected to ecotriplet2 (COM5)
19-10-2020 13:08:07 Sensors Bridge connected to ecotriplet3 (COM6)
19-10-2020 13:08:08 Sensors Bridge connected to dissolvedoxygen (COM7)
19-10-2020 13:08:12 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 13:08:12 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 13:08:12 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 13:08:12 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 13:08:12 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 13:08:12 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 13:08:12 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 13:08:12 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 13:08:12 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 13:08:12 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 13:13:16 Sensors Bridge connected to co2procv (COM3)
19-10-2020 13:13:17 Sensors Bridge connected to ecotriplet1 (COM4)
19-10-2020 13:13:17 Sensors Bridge connected to ecotriplet2 (COM5)
19-10-2020 13:13:18 Sensors Bridge connected to ecotriplet3 (COM6)
19-10-2020 13:13:19 Sensors Bridge connected to dissolvedoxygen (COM7)
19-10-2020 13:14:09 Sensors Bridge connected to co2procv (COM3)
19-10-2020 13:14:10 Sensors Bridge connected to ecotriplet1 (COM4)
19-10-2020 13:14:10 Sensors Bridge connected to ecotriplet2 (COM5)
19-10-2020 13:14:11 Sensors Bridge connected to ecotriplet3 (COM6)
19-10-2020 13:14:12 Sensors Bridge connected to dissolvedoxygen (COM7)
19-10-2020 13:16:02 Sensors Bridge connected to co2procv (COM3)
19-10-2020 13:16:03 Sensors Bridge connected to ecotriplet1 (COM4)
19-10-2020 13:16:03 Sensors Bridge connected to ecotriplet2 (COM5)
19-10-2020 13:16:04 Sensors Bridge connected to ecotriplet3 (COM6)
19-10-2020 13:16:05 Sensors Bridge connected to dissolvedoxygen (COM7)
19-10-2020 13:17:51 Sensors Bridge connected to co2procv (COM3)
19-10-2020 13:17:51 Sensors Bridge connected to ecotriplet1 (COM4)
19-10-2020 13:17:52 Sensors Bridge connected to ecotriplet2 (COM5)
19-10-2020 13:17:53 Sensors Bridge connected to ecotriplet3 (COM6)
19-10-2020 13:17:54 Sensors Bridge connected to dissolvedoxygen (COM7)
19-10-2020 13:18:20 Sensors Bridge connected to port 50000
19-10-2020 13:18:21 Sensors Bridge connected to co2procv (COM3)
19-10-2020 13:18:22 Sensors Bridge connected to ecotriplet1 (COM4)
19-10-2020 13:18:22 Sensors Bridge connected to ecotriplet2 (COM5)
19-10-2020 13:18:23 Sensors Bridge connected to ecotriplet3 (COM6)
19-10-2020 13:18:24 Sensors Bridge connected to dissolvedoxygen (COM7)
19-10-2020 13:22:06 Sensors Bridge connected to port 50000
19-10-2020 13:22:07 Sensors Bridge connected to co2procv (COM3)
19-10-2020 13:22:08 Sensors Bridge connected to ecotriplet1 (COM4)
19-10-2020 13:22:09 Sensors Bridge connected to ecotriplet2 (COM5)
19-10-2020 13:22:09 Sensors Bridge connected to ecotriplet3 (COM6)
19-10-2020 13:22:10 Sensors Bridge connected to dissolvedoxygen (COM7)
19-10-2020 13:27:41 Sensors Bridge connected to port 50000
19-10-2020 13:27:42 Sensors Bridge connected to co2procv (COM3)
19-10-2020 13:27:43 Sensors Bridge connected to ecotriplet1 (COM4)
19-10-2020 13:27:44 Sensors Bridge connected to ecotriplet2 (COM5)
19-10-2020 13:27:44 Sensors Bridge connected to ecotriplet3 (COM6)
19-10-2020 13:27:45 Sensors Bridge connected to dissolvedoxygen (COM7)
19-10-2020 13:29:12 Sensors Bridge connected to port 50000
19-10-2020 13:29:12 Sensors Bridge connected to co2procv (COM3)
19-10-2020 13:29:13 Sensors Bridge connected to ecotriplet1 (COM4)
19-10-2020 13:29:14 Sensors Bridge connected to ecotriplet2 (COM5)
19-10-2020 13:29:15 Sensors Bridge connected to ecotriplet3 (COM6)
19-10-2020 13:29:15 Sensors Bridge connected to dissolvedoxygen (COM7)
19-10-2020 13:30:03 Sensors Bridge connected to port 50000
19-10-2020 13:30:04 Sensors Bridge connected to co2procv (COM3)
19-10-2020 13:30:05 Sensors Bridge connected to ecotriplet1 (COM4)
19-10-2020 13:30:05 Sensors Bridge connected to ecotriplet2 (COM5)
19-10-2020 13:30:06 Sensors Bridge connected to ecotriplet3 (COM6)
19-10-2020 13:30:07 Sensors Bridge connected to dissolvedoxygen (COM7)
19-10-2020 13:30:45 Sensors Bridge connected to port 50000
19-10-2020 13:30:45 Sensors Bridge connected to co2procv (COM3)
19-10-2020 13:30:46 Sensors Bridge connected to ecotriplet1 (COM4)
19-10-2020 13:30:47 Sensors Bridge connected to ecotriplet2 (COM5)
19-10-2020 13:30:47 Sensors Bridge connected to ecotriplet3 (COM6)
19-10-2020 13:30:48 Sensors Bridge connected to dissolvedoxygen (COM7)
19-10-2020 13:30:52 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 13:30:52 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 13:30:52 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 13:30:52 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 13:30:52 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 13:30:53 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 13:30:53 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 13:30:53 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 13:30:53 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 13:30:53 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 13:33:24 Sensors Bridge connected to port 50000
19-10-2020 13:33:24 Sensors Bridge connected to co2procv (COM3)
19-10-2020 13:33:25 Sensors Bridge connected to ecotriplet1 (COM4)
19-10-2020 13:33:26 Sensors Bridge connected to ecotriplet2 (COM5)
19-10-2020 13:33:27 Sensors Bridge connected to ecotriplet3 (COM6)
19-10-2020 13:33:27 Sensors Bridge connected to dissolvedoxygen (COM7)
19-10-2020 13:33:31 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 13:33:31 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 13:33:31 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 13:33:32 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 13:33:32 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 13:33:32 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 13:33:32 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 13:33:32 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 13:33:32 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 13:33:32 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 13:34:21 Sensors Bridge connected to port 50000
19-10-2020 13:34:22 Sensors Bridge connected to co2procv (COM3)
19-10-2020 13:34:23 Sensors Bridge connected to ecotriplet1 (COM4)
19-10-2020 13:34:23 Sensors Bridge connected to ecotriplet2 (COM5)
19-10-2020 13:34:24 Sensors Bridge connected to ecotriplet3 (COM6)
19-10-2020 13:34:25 Sensors Bridge connected to dissolvedoxygen (COM7)
19-10-2020 13:34:29 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 13:34:29 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 13:34:29 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 13:34:29 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 13:34:29 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 13:34:29 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 13:34:29 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 13:34:30 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 13:34:30 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 13:34:30 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 13:34:48 Traceback (most recent call last):
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 296, in read_com
    c = a_serial.readline()
  File "C:\Python38\lib\site-packages\serial\serialwin32.py", line 286, in read
    result_ok = win32.GetOverlappedResult(
KeyboardInterrupt

19-10-2020 13:34:48 Traceback (most recent call last):
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 296, in read_com
    c = a_serial.readline()
  File "C:\Python38\lib\site-packages\serial\serialwin32.py", line 286, in read
    result_ok = win32.GetOverlappedResult(
KeyboardInterrupt

19-10-2020 13:34:49 Traceback (most recent call last):
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 296, in read_com
    c = a_serial.readline()
  File "C:\Python38\lib\site-packages\serial\serialwin32.py", line 286, in read
    result_ok = win32.GetOverlappedResult(
KeyboardInterrupt

19-10-2020 13:34:49 Traceback (most recent call last):
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 296, in read_com
    c = a_serial.readline()
  File "C:\Python38\lib\site-packages\serial\serialwin32.py", line 286, in read
    result_ok = win32.GetOverlappedResult(
KeyboardInterrupt

19-10-2020 13:34:49 Traceback (most recent call last):
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 296, in read_com
    c = a_serial.readline()
  File "C:\Python38\lib\site-packages\serial\serialwin32.py", line 286, in read
    result_ok = win32.GetOverlappedResult(
KeyboardInterrupt

19-10-2020 13:39:10 Sensors Bridge connected to port 50000
19-10-2020 13:39:11 Sensors Bridge connected to co2procv (COM3)
19-10-2020 13:39:11 Sensors Bridge connected to ecotriplet1 (COM4)
19-10-2020 13:39:12 Sensors Bridge connected to ecotriplet2 (COM5)
19-10-2020 13:39:13 Sensors Bridge connected to ecotriplet3 (COM6)
19-10-2020 13:39:13 Sensors Bridge connected to dissolvedoxygen (COM7)
19-10-2020 13:39:17 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 13:39:17 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 13:39:17 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 13:39:17 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 13:39:17 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 13:39:18 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 13:39:18 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 13:39:18 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 13:39:18 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 13:39:18 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 13:39:55 Sensors Bridge connected to port 50000
19-10-2020 13:39:55 Sensors Bridge connected to co2procv (COM3)
19-10-2020 13:39:56 Sensors Bridge connected to ecotriplet1 (COM4)
19-10-2020 13:39:57 Sensors Bridge connected to ecotriplet2 (COM5)
19-10-2020 13:39:58 Sensors Bridge connected to ecotriplet3 (COM6)
19-10-2020 13:39:58 Sensors Bridge connected to dissolvedoxygen (COM7)
19-10-2020 13:40:02 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 13:40:02 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 13:40:02 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 13:40:02 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 13:40:03 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 13:40:03 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 13:40:03 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 13:40:03 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 13:40:03 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 13:40:03 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 13:45:03 Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Python38\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\Python38\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Python38\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "C:\Python38\lib\site-packages\urllib3\util\retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Python38\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Python38\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\Python38\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Python38\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 306, in read_com
    manage_data(data, com, show_no_internet_error)
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 319, in manage_data
    send_to_server(port_name, data)
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 105, in send_to_server
    response = SESSION.post(url, data=data)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python38\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

19-10-2020 13:45:23 Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Python38\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\Python38\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Python38\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "C:\Python38\lib\site-packages\urllib3\util\retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Python38\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Python38\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\Python38\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Python38\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 306, in read_com
    manage_data(data, com, show_no_internet_error)
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 319, in manage_data
    send_to_server(port_name, data)
  File "C:\Users\User\Desktop\sensors_bridge\transfer.py", line 105, in send_to_server
    response = SESSION.post(url, data=data)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python38\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

19-10-2020 14:01:01 Error: 502 Failed to send ecotriplet3 at port COM6. Saving it to local file.
19-10-2020 14:05:29 Sensors Bridge connected to port 50000
19-10-2020 14:05:30 Sensors Bridge connected to co2procv (COM3)
19-10-2020 14:05:31 Sensors Bridge connected to ecotriplet1 (COM4)
19-10-2020 14:05:32 Sensors Bridge connected to ecotriplet2 (COM5)
19-10-2020 14:05:33 Sensors Bridge connected to ecotriplet3 (COM6)
19-10-2020 14:05:33 Sensors Bridge connected to dissolvedoxygen (COM7)
19-10-2020 14:05:37 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 14:05:37 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_co2procv.txt
19-10-2020 14:05:37 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 14:05:37 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet3.txt
19-10-2020 14:05:38 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 14:05:38 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 14:05:38 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_dissolvedoxygen.txt
19-10-2020 14:05:38 Sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
19-10-2020 14:05:38 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet1.txt
19-10-2020 14:05:38 Completed sending backup C:\Users\User\Desktop\sensors_bridge\data\19_10_2020_temp_ecotriplet2.txt
